version: '3'
services:
  app:
    build: .
    ports:
      - "80:80"
    environment:
      - DEBUG=true
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
  redis:
    image: redis:latest