version: '3.9'
services:
  app:
    build: .
    ports:
      - "80:80"
    environment:
      - DEBUG=false
    networks:
      - app_net
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "256M"
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_password
      MYSQL_DATABASE: test
    secrets:
      - db_password
    networks:
      - db_net
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "512M"
  redis:
    image: redis:7.0
    networks:
      - redis_net
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "128M"

networks:
  app_net:
    driver: bridge
  db_net:
    driver: bridge
  redis_net:
    driver: bridge

secrets:
  db_password:
    file: ./secrets/db_password.txt