apiVersion: v1
kind: ConfigMap
metadata:
  name: infurianto-config
  namespace: default
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Hello World</title>
    </head>
    <body>
        <h1>Hello world from Angelina! <3</h1>
    </body>
    </html>