apiVersion: apps/v1
kind: Deployment
metadata:
  name: infurianto-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: infurianto
  template:
    metadata:
      labels:
        app: infurianto
    spec:
      containers:
      - name: infurianto
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html-volume
        configMap:
          name: infurianto-config